services:
  mes:
    container_name: mes
    build: ./
    image: ghcr.io/mervinhemaraju/mauritius-emergency-service-api:local
    platform: linux/arm64
    networks:
      - mes_net
    volumes:
      - ./data:/app/data
    env_file:
      - secrets.env
    expose:
      - 8081
    restart: always

  nginx_mes:
    image: nginx
    container_name: nginx_mes
    platform: linux/arm64
    ports:
      - "8081:80"
    networks:
      - mes_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - mes
    restart: always

networks:
  mes_net:
    name: mes_network
