version: "3.8"

services:
  mes:
    container_name: mes
    build: ./
    image: "docker.pkg.github.com/mervin16/mauritius-emergency-services-api/mes:1.2.4"
    networks:
      - mes_net
    volumes:
      - ./data:/app/data
    env_file:
      - config_local.env
    expose:
      - 5000
    restart: always

  nginx_mes:
    image: nginx
    container_name: nginx_mes
    ports:
      - "5000:80"
    networks:
      - mes_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - mes
    restart: always

networks:
  mes_net:
    name: mes_network
    driver: bridge
