# A dictionary mapping month names variants to their corresponding numerical values
MONTH_NUMBER_MAPPING_VARIANTS = {
    "janvier": 1,
    "january": 1,
    "février": 2,
    "fevrier": 2,
    "february": 2,
    "mars": 3,
    "march": 3,
    "avril": 4,
    "april": 4,
    "mai": 5,
    "may": 5,
    "juin": 6,
    "june": 6,
    "juillet": 7,
    "july": 7,
    "août": 8,
    "aout": 8,
    "august": 8,
    "septembre": 9,
    "september": 9,
    "octobre": 10,
    "october": 10,
    "novembre": 11,
    "november": 11,
    "décembre": 12,
    "decembre": 12,
    "december": 12,
}

# A dictionnary containing all the CEB districts
CEB_DISTRICTS = {
    "blackriver": "Black-River",
    "flacq": "Flacq",
    "grandport": "Grand-Port",
    "moka": "Moka",
    "pamplemousses": "Pamplemousses",
    "plainewilhems": "Plaines-Wilhems",
    "portlouis": "Port-Louis",
    "rivieredurempart": "Riviere-du-Rempart",
    "savanne": "Savanne",
}
