name: Pre-Commit Checks

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
    pre-commit:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
  
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Install Pre-Commit
        run: |
          pip install pre-commit
          pre-commit --version
  
      - name: Run Pre-Commit
        working-directory: "./"
        run: |
          pre-commit run --all-files --verbose --show-diff-on-failure
