name: Python CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Dependencies
        run: pip install -r requirements.txt
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      MAIL_USERNAME: "dummy_username"
      MAIL_PASSWORD: "dummy_password"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: python -m pytest tests/ --junitxml=results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.xml

  post-results:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Post Test Results on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: results.xml
